In [ ]:
#import library
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_validate,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
df=pd.read_csv("/content/insurance_claims.csv")
df.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: float64(2), int64(17), object(21)
memory usage: 312.6+ KB

In [ ]:
df.isnull().sum()

months_as_customer                0
age                               0
policy_number                     0
policy_bind_date                  0
policy_state                      0
policy_csl                        0
policy_deductable                 0
policy_annual_premium             0
umbrella_limit                    0
insured_zip                       0
insured_sex                       0
insured_education_level           0
insured_occupation                0
insured_hobbies                   0
insured_relationship              0
capital-gains                     0
capital-loss                      0
incident_date                     0
incident_type                     0
collision_type                    0
incident_severity                 0
authorities_contacted            91
incident_state                    0
incident_city                     0
incident_location                 0
incident_hour_of_the_day          0
number_of_vehicles_involved       0
property_damage                   0
bodily_injuries                   0
witnesses                         0
police_report_available           0
total_claim_amount                0
injury_claim                      0
property_claim                    0
vehicle_claim                     0
auto_make                         0
auto_model                        0
auto_year                         0
fraud_reported                    0
_c39                           1000
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported', '_c39'],
      dtype='object')

In [ ]:
x = df.drop("fraud_reported", axis=1)
y = df["fraud_reported"]

print(x.head())
print(y.head())

   months_as_customer  age  policy_number policy_bind_date policy_state  \
0                 328   48         521585       2014-10-17           OH
1                 228   42         342868       2006-06-27           IN
2                 134   29         687698       2000-09-06           OH
3                 256   41         227811       1990-05-25           IL
4                 228   44         367455       2014-06-06           IL

  policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  \
0    250/500               1000                1406.91               0
1    250/500               2000                1197.22         5000000
2    100/300               2000                1413.14         5000000
3    250/500               2000                1415.74         6000000
4   500/1000               1000                1583.91         6000000

   insured_zip  ... witnesses police_report_available total_claim_amount  \
0       466132  ...         2                     YES              71610
1       468176  ...         0                       ?               5070
2       430632  ...         3                      NO              34650
3       608117  ...         2                      NO              63400
4       610706  ...         1                      NO               6500

  injury_claim property_claim  vehicle_claim  auto_make auto_model auto_year  \
0         6510          13020          52080       Saab        92x      2004
1          780            780           3510   Mercedes       E400      2007
2         7700           3850          23100      Dodge        RAM      2007
3         6340           6340          50720  Chevrolet      Tahoe      2014
4         1300            650           4550     Accura        RSX      2009

  _c39
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN

[5 rows x 39 columns]
0    Y
1    Y
2    N
3    Y
4    N
Name: fraud_reported, dtype: object

In [ ]:
#spliting the dataset for training and testing
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.3,
    random_state=40
)

In [ ]:
print(x.dtypes)

months_as_customer               int64
age                              int64
policy_number                    int64
policy_bind_date                object
policy_state                    object
policy_csl                      object
policy_deductable                int64
policy_annual_premium          float64
umbrella_limit                   int64
insured_zip                      int64
insured_sex                     object
insured_education_level         object
insured_occupation              object
insured_hobbies                 object
insured_relationship            object
capital-gains                    int64
capital-loss                     int64
incident_date                   object
incident_type                   object
collision_type                  object
incident_severity               object
authorities_contacted           object
incident_state                  object
incident_city                   object
incident_location               object
incident_hour_of_the_day         int64
number_of_vehicles_involved      int64
property_damage                 object
bodily_injuries                  int64
witnesses                        int64
police_report_available         object
total_claim_amount               int64
injury_claim                     int64
property_claim                   int64
vehicle_claim                    int64
auto_make                       object
auto_model                      object
auto_year                        int64
_c39                           float64
dtype: object

In [ ]:
print(x.select_dtypes(include="object").head())

  policy_bind_date policy_state policy_csl insured_sex  \
0       2014-10-17           OH    250/500        MALE
1       2006-06-27           IN    250/500        MALE
2       2000-09-06           OH    100/300      FEMALE
3       1990-05-25           IL    250/500      FEMALE
4       2014-06-06           IL   500/1000        MALE

  insured_education_level insured_occupation insured_hobbies  \
0                      MD       craft-repair        sleeping
1                      MD  machine-op-inspct         reading
2                     PhD              sales     board-games
3                     PhD       armed-forces     board-games
4               Associate              sales     board-games

  insured_relationship incident_date             incident_type  \
0              husband    2015-01-25  Single Vehicle Collision
1       other-relative    2015-01-21             Vehicle Theft
2            own-child    2015-02-22   Multi-vehicle Collision
3            unmarried    2015-01-10  Single Vehicle Collision
4            unmarried    2015-02-17             Vehicle Theft

    collision_type incident_severity authorities_contacted incident_state  \
0   Side Collision      Major Damage                Police             SC
1                ?      Minor Damage                Police             VA
2   Rear Collision      Minor Damage                Police             NY
3  Front Collision      Major Damage                Police             OH
4                ?      Minor Damage                   NaN             NY

  incident_city  incident_location property_damage police_report_available  \
0      Columbus     9935 4th Drive             YES                     YES
1     Riverwood       6608 MLK Hwy               ?                       ?
2      Columbus  7121 Francis Lane              NO                      NO
3     Arlington   6956 Maple Drive               ?                      NO
4     Arlington       3041 3rd Ave              NO                      NO

   auto_make auto_model
0       Saab        92x
1   Mercedes       E400
2      Dodge        RAM
3  Chevrolet      Tahoe
4     Accura        RSX

In [ ]:
x["incident_date"] = pd.to_datetime(
    x["incident_date"],
    errors="coerce"
)

x["incident_year"] = x["incident_date"].dt.year
x["incident_month"] = x["incident_date"].dt.month
x["incident_day"] = x["incident_date"].dt.day

x = x.drop(columns=["incident_date"])

In [ ]:
x = pd.get_dummies(x, drop_first=True, dtype=int)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [ ]:
print(x_train.isnull().sum())

months_as_customer       0
age                      0
policy_number            0
policy_deductable        0
policy_annual_premium    0
                        ..
auto_model_Tahoe         0
auto_model_Ultima        0
auto_model_Wrangler      0
auto_model_X5            0
auto_model_X6            0
Length: 2098, dtype: int64

In [ ]:
print("Missing values:", x_train.isnull().sum().sum())

Missing values: 800

In [ ]:
x = x.dropna(axis=1, how="all")

print("Shape after removing empty columns:", x.shape)

Shape after removing empty columns: (1000, 2097)

In [ ]:
x = pd.get_dummies(x, drop_first=True, dtype=int)

In [ ]:
from sklearn.impute import SimpleImputer
import pandas as pd

imputer = SimpleImputer(strategy="median")

x = pd.DataFrame(
    imputer.fit_transform(x),
    columns=imputer.get_feature_names_out(),
    index=x.index
)

print("Remaining missing values:", x.isnull().sum().sum())
print("Final shape:", x.shape)

Remaining missing values: 0
Final shape: (1000, 2097)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(max_iter=1000)

LR.fit(x_train, y_train)

print("Model trained successfully!")

Model trained successfully!

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
LR=LogisticRegression(max_iter=1000)
LR.fit(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [ ]:
#Testing Accuracy
y_pred=LR.predict(x_test)
accuracy=accuracy_score(y_pred,y_test)
print("Testing Accuracy:",accuracy)

Testing Accuracy: 0.725

In [ ]:
#training accuracy
y_pred_train=LR.predict(x_train)
accuracy_train=accuracy_score(y_pred_train,y_train)
print("Testing Accuracy:",accuracy_train)

Testing Accuracy: 0.7575

In [ ]:
#validation Acuuracy
val_accuracy=cross_val_score(LR,
    x_train,y_train,cv=5
)
print("Validation Accuracy: ",val_accuracy.mean())

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Validation Accuracy:  0.7562500000000001

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
#Random Forest Classifier
RF=RandomForestClassifier(
    n_estimators=200,max_depth=10,min_samples_leaf=10,verbose=1,n_jobs=1
)

In [ ]:
RF.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done 199 tasks      | elapsed:    0.9s
[Parallel(n_jobs=1)]: Done 200 out of 200 | elapsed:    0.9s finished

RandomForestClassifier(max_depth=10, min_samples_leaf=10, n_estimators=200,
                       n_jobs=1, verbose=1)

In [ ]:
y_pred_rf=RF.predict(x_test)
accuracy_rf=accuracy_score(y_pred_rf,y_test)
print("Testing Accuracy:",accuracy_rf)

Testing Accuracy: 0.725

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 199 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done 200 out of 200 | elapsed:    0.1s finished

In [ ]:
y_pred_train_rf=RF.predict(x_train)
accuracy_train_rf=accuracy_score(y_pred_train_rf,y_train)
print("Testing Accuracy:",accuracy_train_rf)

Testing Accuracy: 0.76

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 199 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 200 out of 200 | elapsed:    0.0s finished

In [ ]:
#Gradient Boosting
gb=GradientBoostingClassifier(
    n_estimators=200,min_samples_leaf=10,learning_rate=0.1,random_state=42
)
gb.fit(x_train,y_train)

GradientBoostingClassifier(min_samples_leaf=10, n_estimators=200,
                           random_state=42)

In [ ]:
y_pred_gb=gb.predict(x_test)
accuracy_gb=accuracy_score(y_pred_gb,y_test)
print("Testing Accuracy:",accuracy_gb)

Testing Accuracy: 0.775

In [ ]:
y

0      Y
1      Y
2      N
3      Y
4      N
      ..
995    N
996    N
997    N
998    N
999    N
Name: fraud_reported, Length: 1000, dtype: object

In [ ]:
y_pred_train_gb=gb.predict(x_train)
accuracy_train_gb=accuracy_score(y_pred_train_gb,y_train)
print("Training Accuracy:",accuracy_train_gb)

Training Accuracy: 0.9875

In [ ]:
valid_gb=cross_val_score(
    gb,x_train,y_train,cv=5
)
print("Validation Accuracy: ",valid_gb.mean())

Validation Accuracy:  0.81375

In [ ]:
confusion_matrix(y_pred_gb,y_test)

array([[130,  30],
       [ 15,  25]])

In [ ]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.32.3)

In [ ]:
print("Target values:", y_train.unique())
print("Target data type:", y_train.dtype)
print("Missing values:", y_train.isnull().sum())

Target values: ['N' 'Y']
Target data type: object
Missing values: 0

In [ ]:
print(y.value_counts(dropna=False))

fraud_reported
N    753
Y    247
Name: count, dtype: int64

In [ ]:
y_train = y_train.map({'N': 0, 'Y': 1})
y_test = y_test.map({'N': 0, 'Y': 1})

print(y_train.unique())
print(y_test.unique())

[0 1]
[0 1]

In [ ]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=100,
    max_depth=8,
    learning_rate=0.2,
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(x_train, y_train)

print("XGBoost model trained successfully!")

XGBoost model trained successfully!

In [ ]:
from sklearn.metrics import accuracy_score

y_pred = xgb.predict(x_test)

print("Validation Accuracy:", accuracy_score(y_test, y_pred))

Validation Accuracy: 0.79

In [ ]:
y_pred_xgb=xgb.predict(x_test)
accuracy_xgb=accuracy_score(y_pred_xgb,y_test)
print("Testing Accuracy:",accuracy_xgb)

Testing Accuracy: 0.79

In [ ]:
y_pred_train_xgb=xgb.predict(x_train)
accuracy_train_xgb=accuracy_score(y_pred_train_xgb,y_train)
print("Training Accuracy:",accuracy_train_xgb)

Training Accuracy: 1.0

In [ ]:
import joblib

joblib.dump(
    {"model": xgb, "feature": list(x.columns)},
    "insurance.joblib",
    compress=3
)

['insurance.joblib']